server:
  port: ${PORT}
  servlet:
    encoding:
      charset: UTF-8

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem/test
    username: sa
    password:
    hikari:
      maximum-pool-size: 4